version: '3'
services:
  stock_postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/stock/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
